### ISSUE TITLE
Targeting S+

### ISSUE THREAD

**Issue by michaelCrusem** [umair13adil/RxLogs#5]
Hi,

I got this error when I add RxLogs dependency :
 Process: amf.ambadge.debug, PID: 30075
    java.lang.IllegalArgumentException: amf.ambadge.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

Did you planned to correct it ?

Thank you

**Comment by umair13adil** [comment]
This is fixed in the latest release 1.0.17+
